### ISSUE TITLE
Add support for HAMT directories

### ISSUE THREAD

**Issue by Gozala** [ipld/js-unixfs#37]
JS-ipfs [starts sharing directories once directory has more that 1000](https://github.com/ipfs/js-ipfs-unixfs/blob/master/packages/ipfs-unixfs-importer/src/options.js#L36) entries, so that it fits in block limit.

We need to support sharded directories for the same reason.

**Comment by Gozala** [comment]
Blocked on getting coverage in https://github.com/Gozala/perma-map/pull/1 to 100% so it can land and be released

**Comment by Gozala** [comment]
@alanshaw so have some code laying around but I don't think it's very useful. Most of basically does what I pulled out into separate repo https://github.com/Gozala/perma-map/pull/1 idea was to rewrite the directory writer to use the hamt from the get go. Then on `close` asses whether it's small enough to be just encoded as flat directory (current behavior) or encode it as UnixFS HAMT. Also note that HAMT implementation is more generic and optimal that one used by UnixFS, however there is [unixfs module](https://github.com/Gozala/perma-map/pull/1/files#diff-dc9541c7328bd8a9572a4b8817d256898f7170866fe26e31691d94f9d7d41e36) in the repo that can map into UnixFS expected DAG layout and some tests verifying it produces same result as unixfs-importer.

**Comment by alanshaw** [comment]
I have a [script to create a fixture](https://gist.github.com/alanshaw/e4bf69a3c4067992101a5b2801410b30) from a CAR file with a HAMT sharded directory in it.

Idea is to generate a fixture do an `ipfs add -r big-dir` and then `ipfs dag export bafy... > my.car` and use the script to generate the fixture from the data.

I'm currently encountering a bug where some _values_ are coming back incorrectly - they're the  _key_ not the _value_ 😱:

<img width="485" alt="Screenshot 2023-03-07 at 15 33 55" src="https://user-images.githubusercontent.com/152863/223470393-4dc18136-683a-40ad-bd26-dee9731db562.png">

**Comment by alanshaw** [comment]
Resolved by https://github.com/ipld/js-unixfs/pull/41
